//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveLeakCommentSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveLeakCommentSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Badwordslist.txt.
        /// </summary>
        internal static string BadWordFile {
            get {
                return ResourceManager.GetString("BadWordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to resume the last search?.
        /// </summary>
        internal static string BeginSearch_resume_last_search {
            get {
                return ResourceManager.GetString("BeginSearch_resume_last_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.liveleak.com/comment?a=view_comment&amp;comment_id=.
        /// </summary>
        internal static string CommentUrl {
            get {
                return ResourceManager.GetString("CommentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Data rows imported..
        /// </summary>
        internal static string Data_rows_imported {
            get {
                return ResourceManager.GetString("Data_rows_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to export current state only?.
        /// </summary>
        internal static string export_current_state_only {
            get {
                return ResourceManager.GetString("export_current_state_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export State only?.
        /// </summary>
        internal static string Export_State_only {
            get {
                return ResourceManager.GetString("Export_State_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter multiple usernames seperated by commas
        ///Example: user1,user2,user3
        ///.
        /// </summary>
        internal static string Find_User_ToolTip {
            get {
                return ResourceManager.GetString("Find_User_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete.
        /// </summary>
        internal static string FrmCommentMonitor_Export_complete {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Export_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file missing.
        /// </summary>
        internal static string FrmCommentMonitor_Import_Data_file_missing {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Import_Data_file_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to include all results?.
        /// </summary>
        internal static string FrmCommentMonitor_Import_include_all_results {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Import_include_all_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import over existing results.
        /// </summary>
        internal static string FrmCommentMonitor_Import_over_existing_results {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Import_over_existing_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing will erase the results from the grid, are you sure you want to continue?.
        /// </summary>
        internal static string FrmCommentMonitor_Importing_will_erase_the_results {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Importing_will_erase_the_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This location already contains data, continuing will append data to any existing files..
        /// </summary>
        internal static string FrmCommentMonitor_location_already_contains_data {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_location_already_contains_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liveleak comment search has stopped while searching .
        /// </summary>
        internal static string FrmCommentMonitor_Search_Stopped {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Search_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output directory.
        /// </summary>
        internal static string FrmCommentMonitor_select_an_output_directory {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_select_an_output_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an input directory.
        /// </summary>
        internal static string FrmCommentMonitor_select_input_directory {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_select_input_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder is not Empty.
        /// </summary>
        internal static string FrmCommentMonitor_Target_not_Empty {
            get {
                return ResourceManager.GetString("FrmCommentMonitor_Target_not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import from this location because it&apos;s missing the state file!.
        /// </summary>
        internal static string FrmCommentMonitort_Cannot_import {
            get {
                return ResourceManager.GetString("FrmCommentMonitort_Cannot_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconMain {
            get {
                object obj = ResourceManager.GetObject("IconMain", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import complete.
        /// </summary>
        internal static string Import_complete {
            get {
                return ResourceManager.GetString("Import_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to include all results?.
        /// </summary>
        internal static string include_all_results {
            get {
                return ResourceManager.GetString("include_all_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all results or just state?.
        /// </summary>
        internal static string Include_all_results_or_just_state {
            get {
                return ResourceManager.GetString("Include_all_results_or_just_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume previous search.
        /// </summary>
        internal static string Resume_previous_search_Caption {
            get {
                return ResourceManager.GetString("Resume_previous_search_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Data rows Exported..
        /// </summary>
        internal static string rows_Exported {
            get {
                return ResourceManager.GetString("rows_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while I locate recent comments..
        /// </summary>
        internal static string ShowHidePopup_Please_wait {
            get {
                return ResourceManager.GetString("ShowHidePopup_Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status was exported.
        /// </summary>
        internal static string Status_Exported {
            get {
                return ResourceManager.GetString("Status_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status imported.
        /// </summary>
        internal static string Status_imported {
            get {
                return ResourceManager.GetString("Status_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCS.
        /// </summary>
        internal static string TrayIcon_Text_LCS {
            get {
                return ResourceManager.GetString("TrayIcon_Text_LCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect. Check connectivity..
        /// </summary>
        internal static string Unable_to_connect {
            get {
                return ResourceManager.GetString("Unable_to_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Error.
        /// </summary>
        internal static string Web_Error {
            get {
                return ResourceManager.GetString("Web_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a username.
        /// </summary>
        internal static string You_must_enter_a_username {
            get {
                return ResourceManager.GetString("You_must_enter_a_username", resourceCulture);
            }
        }
    }
}
